### ISSUE TITLE
Mircoblog issues

### ISSUE THREAD

**Issue by takshingli810** [cloverharvest/microblog#1]
1. Your page refreshes so the words don't post

2. The background probably change it to cover and see if it will cover the whole page

3. Create a div box so you can store the words :D

**Comment by cloverharvest** [comment]
Addresses div issues wip, partial responsiveness, words post to div, wip. Still need to work on local storage.

index.html
`<!DOCTYPE html>
<html>

	<head>
	<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" conten="width=device-width, initial-scale=1">
	 
	<title>Ticker</title>



	<link rel="stylesheet" type="text/css" href="css/style.css">
	
	</head>

	<body>
		
		  <form>

		  	<header>Ticker</header>
		  	<hr>
		  	<div>
		    <h2>What's on your mind?</h2>
		    <input id="userInput" type="text" placeholder="How's it going?" />
		    </div>
		    <div>
			<input id="prettybutton" type="button" value="Post"onclick="insert()" />
			</div>

		    </form>
			<hr>
			<h2> Most Recent Posts </h2>
	  		<div>
	  			<textarea id="display" type="text"></textarea>
		    </div>
	  		</div>

		  
	</body>	
	<script>

		var recentPosts  = [];


		var userInput  = document.getElementById("userInput");

		var messageBox  = document.getElementById("display");

		

		function insert( ) {
	 	
	 	recentPosts.push(userInput.value);
	  
	 	clearAndShow();
		}

		function clearAndShow () {
	  	// Clear our fields
	  	userInput.value = "";
	  
	  	// Show our output
	  	messageBox.innerHTML = "";
	  
	  	messageBox.innerHTML += recentPosts.join("\n");
	 
		}
	</script>
		
</html>
`
style.css
`body {
    
    background-image: url("../image/pool-coron1.png");
    color: pink;

}

header {
	font-size: 50px;
	font-family: Avenir;
	text-align: center;
}

h2 {
	font-size: 30px;
	font-family: Avenir;
	text-align: center;	
}

#userInput {
	display: block;
    margin-left: auto;
    margin-right: auto;
    min-height:100px;
    min-width: 600px;
    border-radius: 5px;
    background-color: #d3d3d3;
    margin-bottom: 15px;
}

#prettybutton {
	display: block;
    margin-left: auto;
    margin-right: auto;
    min-height:30px;
    min-width: 50px;
    border-radius: 10px;
    border-spacing: 5px;
    margin-bottom: 10px;
}

#display {
	display: block;
    margin-left: auto;
    margin-right: auto;
    min-height:100px;
    min-width: 600px;
    border-radius: 5px;
    background-color: #d3d3d3;
    margin-bottom: 15px;    
}`
